server:
  port: 8080
  servlet:
    context-path: /dim
logging:
  level: 
    com.singlethreadzzz.dim: info
  file: logs/dim.log
spring:
  resources:
    static-locations: classpath:/static/
    cache:      period: 0
  mvc: 
    static-path-pattern: /static/**
    favicon:      enabled: false
  thymeleaf: 
    cache: false
    suffix: .html
    prefix: classpath:/templates/
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dim?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: dim
    password: dim
    driver-class-name: com.mysql.cj.jdbc.Driver
  banner:
    location: classpath:/static/banner/banner.txt
mybatis:
  type-aliases-package: com.singlethreadzzz.dim.domain